# Generated by Django 4.0.4 on 2022-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ('userid',),
            },
        ),
    ]
