# Generated by Django 4.0.4 on 2022-05-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
