# Generated by Django 4.0.4 on 2022-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_list',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'item_list',
            },
        ),
    ]
