# Generated by Django 4.0.4 on 2022-05-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneApp', '0002_alter_userinfo_options_alter_userinfo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
