# Generated by Django 4.0.4 on 2022-06-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneApp', '0002_item_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='refrigerator_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='capstoneApp.item_list')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='capstoneApp.userinfo')),
            ],
            options={
                'db_table': 'refrigerator_item',
            },
        ),
    ]
